# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: codediary
email: 616577818@qq.com
description: > # xiaoda的前端笔记
baseurl: "/codediary" # the subpath of your site, e.g. /blog
url: "http://xiaoda.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  xiaoda

# Build settings
markdown: kramdown
